version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - microservices-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microservices
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 3s
      retries: 5

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: timescale
      POSTGRES_PASSWORD: timescale
      POSTGRES_DB: analytics
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U timescale']
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  microservices-network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  timescaledb_data:
